### ISSUE TITLE
Quantize scheme for FPGA

### ISSUE THREAD

**Issue by Junsong-Wang** [ppwwyyxx/tensorpack#14]
This paper uses round((2^k-1)x)/(2^k-1) to quantize x, which may be not suitable for FPGA to represent. For example, if k=2, the quantized valve is 0, 0.33, 0.67, 1, however FPGA only could represents, 0, 0.25, 0.5, 0.75, if not using lookup table.

**Comment by ppwwyyxx** [comment]
A linear operation (convolution or gemm) on [0,0.33,0.67,1] can be computed, by first applying the operation on 3 * [0,0.33,0.67,1] = [0,1,2,3] and then a linear transform. Since [0,1,2,3] are all fixed-point integers of k bit, the operands in the first part can be efficiently  represented and computed on FPGA.

**Comment by Junsong-Wang** [comment]
Thanks for your reply,  since we implement it in FPGA with pipeline feature. The output of the current feature will directly feed to the next layer.  For example, we use 2 bits to represent the weights, according what you mentioned, the weights will be scaled by 3 in FPGA,. After the operation, we usually need to do the bit trunc operation (divided by 3), however 3 is not easy to trunc.

**Comment by ppwwyyxx** [comment]
In our current settings, only the expensive operations (convolution & gemm) are performed in low-bitwidth. The elementwise scaling and nonlinearity are still in floating point.

**Comment by Junsong-Wang** [comment]
I see, do you think the following scheme is also okay to quantize x
1. clip it to range [-1, (2^(k-1) - 1)/2^(k-1)], since k bits can only represent -2^(k-1) to 2^(k-1) -1 
2. quantize by round(x*2(k-1)), and this is the integer could be used in FPGA.

**Comment by zsc** [comment]
In our FPGA implementation, we have avoided all floating point computations.

Conceptually, the output of conv is "k X + b", where X contains only low bitwidth integer numbers and "k" and "b" are floating point numbers,  and then a quantizing NL is applied. W.l.o.g., we next assume activations are 2-bit, then there will be only 4 possible values. We can write a program to find a few integer thresholds so that we can use integer comparisons X > th1, th1 > X > th2, th2 > X > th3, th3 > X to construct the 2-bit activations. More details of the above method will appear in an upcoming arXiv paper.
