### ISSUE TITLE
How to use tfdbg with tensorpack?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#191]
The tensorflow document shows the way to use tfdbg:
```
sess = tf_debug.LocalCLIDebugWrapperSession(sess)
```
In tensorpack, where should I wrap sess with this debug wrapper?
Thanks!

**Comment by ppwwyyxx** [comment]
For the moment you can hack https://github.com/ppwwyyxx/tensorpack/blob/master/tensorpack/train/base.py#L133.

Customized session creation is available in prediction time, but not in training right now. I'll try to fix it.

**Comment by ppwwyyxx** [comment]
Now you can pass an optional `session_creator` in `TrainConfig`. In theory you can choose what session to use for the entire training as long as you write a SessionCreator yourself.
To create a debug session, [`SessionCreatorAdapter`](http://tensorpack.readthedocs.io/en/latest/modules/tfutils.html#tensorpack.tfutils.sesscreate.SessionCreatorAdapter) may help you. You can use:
```python
SessionCreatorAdapter(NewSessionCreator(), 
    lambda sess: tf_debug.LocalCLIDebugWrapperSession(sess, other_options))
```

I also just found there is a debug hook in tensorflow, so an easier way might be just to convert the hooks to callbacks:
```python
        callbacks=[
            HookToCallback(tf_debug.LocalCLIDebugHook()), ...
```

I never used tf_debug so there might be usage I'm not covering. Please leave a note if you found tensorpack makes it harder to do something you could have done easier with tensorflow.

**Comment by JesseYang** [comment]
I use the imagenet-resnet.py to test tf_debug in tensorpack. I try the first method, which use SessionCreatorAdapter to create a session_creator and pass it to TrainConfig. Following the instructinos in tensorflow document, https://www.tensorflow.org/programmers_guide/debugger, I get an error when input 'run' command:
```
Traceback (most recent call last):
  File "imagenet-resnet.py", line 261, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/home/user/tensorflow_workspace/tensorpack/tensorpack/train/base.py", line 91, in train
    self.setup()
  File "/home/user/tensorflow_workspace/tensorpack/tensorpack/train/base.py", line 127, in setup
    self.sess.run(init_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/wrappers/framework.py", line 448, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 264, in on_run_end
    self._dump_root, partition_graphs=partition_graphs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 451, in __init__
    raise IOError("Dump root directory %s does not exist" % dump_root)
IOError: Dump root directory /tmp/tfdbg_ri8gw6 does not exist
```
I also tried with the tf_debug example given by tensorflow:
```
python -m tensorflow.python.debug.examples.debug_mnist --debug
```
and it works fine.

This issue https://github.com/tensorflow/tensorflow/issues/7615 mentions the similar problem, but with the example given by tensorflow and in Windows platform.

**Comment by ppwwyyxx** [comment]
I'll take a look. The second method should work fine.

**Comment by ppwwyyxx** [comment]
The reason is that:
1. The default session config being used doesn't allow soft placement (fixed above)
2. When tensor placement failed, TensorFlow doesn't give the correct error message. (will open an issue in tensorflow)

**Comment by JesseYang** [comment]
Thanks a lot! Now it works fine!!

**Comment by ppwwyyxx** [comment]
To future users: the best way to use `tfdbg` is to add this callback to your training callbacks:
```
callbacks=[
    ...,
    TFLocalCLIDebugHook()
]
```
See docs at: https://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.TFLocalCLIDebugHook

**Comment by shf3125** [comment]
I might be wrong, but I think there might be a problem (pseudo-bug?) with the option of passing `LocalCLIDebugHook` optional arguments. 
This is probably easily fixed by passing the `**kwargs` passed into `TFLocalCLIDebugHook` into the super-initializer, i.e: `super(TFLocalCLIDebugHook, self).__init__(tfdbg.LocalCLIDebugHook(**kwargs))`.
Example use-case: changing the `dump_root`.
I might be missing some complications and intricate nuances, but for now I've added the change above in my code and it seems to be working fine.

Great work BTW!

**Comment by ppwwyyxx** [comment]
Thanks! Now it should be fixed

**Comment by shf3125** [comment]
That was extremely fast. Thanks!
On a different topic, (and let me know if this should be opened via a new issue) - It seems there's some incompatibility between TP multi-gpu training and tfdbg. I don't know exactly what the issue is, but it's probably something to do with the tower-context name-scopes, because the tfdbg process fails with an error regarding multiple with the same name...(specifically the multiplicity of the repeated node is the same number of gpus in usage).
This is important because when debugging the rise of NaNs, reducing the number of gpus effectively reduces the batch size which in turn can cause numerical instability NaNs which have nothing to do with the original problem being investigated.
Hope that's a clear enough description of the problem, let me know if more details are needed or if this should be raised in a different format or context.

**Comment by ppwwyyxx** [comment]
Please open an issue with details.

The tfdbg hook does work with a simple multi-gpu example, but there may be other edge cases.
