### ISSUE TITLE
add option to set a constant random seed for deterministic results

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#196]
seems that the random seed always involves the system clock and i could not find a way to set a constant seed to get deterministic results for debugging. (also, please let me know if i am opening too many issues. maybe we should have a mailing list or forum?)

**Comment by ppwwyyxx** [comment]
Just added a function `utils.fix_rng_seed` in 546af8b2b3b0dd82b0.
You'll also need to avoid any kind of parallelism:
1. set 1 inter/intra op parallelism thread in session config
2. don't use any kind of prefetch
And set seed at the beginning of your program by both `fix_rng_seed` and `tf.set_random_seed`.

And this still cannot guarantee deterministic results, they just make things more deterministic.
Because a lot of common ops (both on GPU and CPU) are non-deterministic. https://github.com/tensorflow/tensorflow/issues/3103
