### ISSUE TITLE
Gaussian Deformation and the Dataset state

### ISSUE THREAD

**Issue by tmquan** [ppwwyyxx/tensorpack#203]
Hi tensorpack, 

What does the gaussian deformation do exactly? Is it similar to Elastic Deformation?
If that is the case, can we alter the magnitude as well as the size of randomly generated grid?

And does the dataset perform the deformation on the *original* data as the iteration increases?
For example, original dataset _dset_ after the first iteration, has been applied some rotations, deformations, etc.  Can we guarantee that in the next iteration, it will perform on the original data but not on the augmented data after iteration 1? (Probably, reset state of the dset will work but I am not sure)

Best regards,

**Comment by ppwwyyxx** [comment]
It generates a continuous vector field of NxM so that it gives each pixel a small displacement but continuous in spatial domain. The field is generated by a mixture of gaussian centered at several spatial locations.

You can adjust the [parameters](http://tensorpack.readthedocs.io/en/latest/modules/dataflow.imgaug.html#tensorpack.dataflow.imgaug.GaussianDeform).

Augmentors doesn't gurantee they don't modify input image. They can do whatever to the input to speed up their processing. This specific augmentor doesn't modify the input image, though.
To avoid the modification goes to your original images (in case you keep them persistent in memory, for example), you can yield a deepcopy in your first dataflow.

**Comment by ppwwyyxx** [comment]
Just give it a second thought. Maybe it's not a very good idea to use a dangerous default, allowing the augmentors to modifiy the image. 
Maybe we should use a safe default (make a copy explicity) and allow turning it off when users know it's OK.

**Comment by ppwwyyxx** [comment]
FYI, added a "copy" option to AugmentImageComponent but still defaults to false now.

**Comment by tmquan** [comment]
Hi @ppwwyyxx , 

I would like to revisit this one and working on the image segmentation. 
Specifically, I would like to implement a custom function on image augmentation which is so-called Elastic Deformation since the Gaussian Deformation is not robust to my problem since it requires the higher accuracy. 

In Elastic Deformation, both 3-channel input and output images need to used the *same* seed number to generate the same vector flow from numpy.
Is it straightforward to and such this customization? An example of interface could be helpful a lot. 

Thanks so much.

**Comment by ppwwyyxx** [comment]
```python
class MyAug:
   def _get_augment_params(self, img):
        return any params that have to be kept same for both input and output
    def _augment(self, img, params):
        return new_img using img and params

df = MyDataFlow() # produce [input, output]
df = AugmentImageComponents(df, [MyAug()], (0,1))
```

**Comment by ppwwyyxx** [comment]
Thanks! The results look interesting. I should try it some day.
Please note that, I added models or augmentors only when they are very common (or sometimes for my personal convenient). I found everyone likes to do augmentation very differently, but then it's very hard for me to maintain all the pieces.
The nice thing is that you can just import and use your augmentor without adding it into tensorpack. I also had a bunch of private code with different ideas I tried, and there are also several augmentors in `examples/` but not in the library. Because I'd rather keep the main library small and only include the common extensions as examples.

**Comment by tmquan** [comment]
ElasticDeform is quite common in biomedical image processing, especially in segmentation. 
If you look into the original U-Net paper, the authors also leveraged it intensively. 

It is good to know that the main library should be kept small and common :)
I will close this issue for other people would like to perform their own custom augmentations. 

Bests,

**Comment by PatWie** [comment]
I vote for adding this to the library. 
@tmquan 
Maybe the best way is to add an example and define it directly there.

**Comment by tmquan** [comment]
@PatWie : I am using the image2image translation for debugging the segmentation problem. 
However, I met the issue such that discriminator curve and generator curve are not going as expected. 
Once it is done, I will make a pull request :)

**Comment by zxpeter** [comment]
Hi @tmquan ,
Thanks for the script of ElasticDeformation.
While implementing it, I find your code may just suit for the square image, it works for me after changed the following lines:
```
DU = cv2.resize(du, (shape[-2], shape[-2])) 
DV = cv2.resize(dv, (shape[-2], shape[-2])) 
X, Y = np.meshgrid(np.arange(shape[0]), np.arange(shape[1]))
```
to
```
DU = cv2.resize(du, (shape[1], shape[0])) 
DV = cv2.resize(dv, (shape[1], shape[0])) 
X, Y = np.meshgrid(np.arange(shape[1]), np.arange(shape[0]))
```
