### ISSUE TITLE
incorrect_vector tensor

### ISSUE THREAD

**Issue by prashantsingh905** [ppwwyyxx/tensorpack#230]
does anybody have idea about this error
`KeyError: "The name 'towerp0/incorrect_vector:0' refers to a Tensor which does not exist. The operation, 'towerp0/incorrect_vector', does not exist in the graph."`

i have print every tensor and none of them is towerp0/incorrect_vector:0. stiil can't figure where is getting created and why?
Here is my code ...just change the extension to .py
[cifar10-resnet.docx](https://github.com/ppwwyyxx/tensorpack/files/922591/cifar10-resnet.docx)

**Comment by ppwwyyxx** [comment]
`ClassificationError` by default looks for this tensor in the graph. Otherwise it doesn't know "what error" to compute (e.g. you can have many "errors" in your model).

For example [here](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L207) it reports two errors, and the two tensors are defined [here](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py#L117).

See the [documents of ClassificationError](http://tensorpack.readthedocs.io/en/latest/modules/callbacks.html#tensorpack.callbacks.ClassificationError)

**Comment by prashantsingh905** [comment]
Thanks ..i got the concept now.
