### ISSUE TITLE
Multi-Task Learning

### ISSUE THREAD

**Issue by laceyg** [ppwwyyxx/tensorpack#35]
In reference to #29.

I am also interested in implementing a multi-task learning model using tensorpack - similar to the "alternating training" example in https://jg8610.github.io/Multi-Task/.  In this example, there are 2 different datasets for 2 tasks, and we want to train a model which uses 1 shared layer, and 1 task-specific layer for each task.  While the example using plain tensorflow is clear, I am not sure what the best approach is using tensorpack.

If we generate two different DataFlow objects such that each generates different data for each task, how would you use the `SyncMultiGPUTrainer` with two different DataFlow objects?  Since this trainer uses the `QueueInputTrainer` is it possible to be enqueuing two different DataFlow objects?

Also, for the task specific layers, would it better to use separate layers with separate cost functions (as in the example) or a single layer with selectable weights?  How would you tell the trainer to select the appropriate weights during training?

Any help / advice is appreciated.

**Comment by ppwwyyxx** [comment]
Yes, one major assumption in this framework is that you have __one__ cost function to optimize. So joint training of multi-task is easy, but alternative training and GAN style training is, although possible, a bit hacky. I'll think about what a proper abstraction is, to allow a model with multiple costs, but here is what can be done now:

Two DataFlow is equivalent to one DataFlow with an indicator, e.g., you have a dataflow which produces
[data1, label1], another produces [data2, label2]. Writing a DataFlow which produces [data1, label1, data2, label2, True/False] is sufficient for the model to know which cost to use and how to compute it. Then you can setup a model with 5 `InputVar` (the last is a `tf.bool`) and use `cost = tf.cond(indicator, get_loss1, get_loss2)`. 

This should work fine in terms of computation cost, because `tf.cond` has lazy evaluation of its arguments `fn1` and `fn2`, so you won't waste any computation, if you write something like:
```python
data1, label1, data2, label2, indicator = inputs
# no code should be outside of the loss functions
def loss1():
    return whatever_model_with_cost(data1, label1)
def loss1():
    return whatever_model_with_cost(data2, label2)
self.cost = tf.cond(indicator, loss1, loss2)
```

However, the hacky part is that the mixed DataFlow has to produce some garbage data for the unused inputs, and pass this garbage data to the graph. Because with `tf.cond`, the graph would still assume the cost depends on both loss1 and loss2 and will require the user to feed some inputs for both losses. 

So the only inefficient part is generating and feeding garbage data for the unused inputs. If the inputs for your different tasks happen to have the same shape (or just same rank) you can use the same `InputVar` for both tasks, then there will be nothing inefficient. Otherwise you can define your `InputVar` with partial shape and only feed the minimum possible tensor to reduce the data feeding cost (although the cost won't be significant), but this is just not very elegant.

**Comment by laceyg** [comment]
Thanks for the helpful advice.  This method seems to work, but I am having one issue with regards to `tf.cond`.  In my model (similar to DoReFa), I have the indicator read in as an input for each data point:

```
def _get_input_vars(self):
    return [InputVar(tf.float32, [None, 224, 224, 3], 'input'),
            InputVar(tf.int32, [None], 'label'),
            InputVar(tf.bool, [None], 'indicator') ]
```

This indicator is used, as discussed, to condition the loss function:

```
def _build_graph(self, input_vars):
        image, label, indicator = input_vars
        ...
        self.cost = tf.cond(indicator, cost_1, cost_2)
```

Meaning that the predicate for `tf.cond` is a tensor of shape (?,) whereas it expects a boolean:

```
ValueError: Shapes (?,) and () are not compatible
```

Is there a proper way to format the predicate to get around this error?  Also, is there a nice way to confirm that `tf.cond` is using the correct loss function for each iteration?

**Comment by ppwwyyxx** [comment]
You want different tasks for different samples in a batch, not different tasks for different batches. This is completely different.
To do what you want you can use tf.select on the two cost vectors. And it'll always compute both costs, because you cannot only compute part of a tensor, not in any existing libraries. Alternatively you can split your batch to two based on the indicator,  compute two costs and return a sum.

**Comment by laceyg** [comment]
Yes I see what you are saying, `tf.select` is more appropriate for an application using different samples in a batch (though one could restructure the problem using both methods).  What I was wondering was more about the correct syntax involved in using `indicator` of shape `(?,)` with an unknown dimension in `tf.select` or `tf.cond`, when the cost vectors are of shape `()`.  For example, the following would get around this error, but I believe is only using the indicator associated with the 0th data for each batch:

```
self.cost = tf.select(indicator[0], cost_1, cost_2)

**Comment by ppwwyyxx** [comment]
If you want different tasks for different samples, then your `cost` should certainly be a vector of shape `(?,)` as well. `tf.select` only works for tensors of the same shape.

**Comment by ppwwyyxx** [comment]
Now you can do alternated multi-cost optimization by implementing the trainer logic in a separate trainer class. See examples of [Generative Adversarial Networks](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/GAN).
