### ISSUE TITLE
Congrats for 1000 Stars!

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#366]
Abusing this issue feature of GitHub: I would like to just thank you for providing this nice piece of code which helps to build and train models faster. Especially, when the submission deadline is approaching firing up multiple GPUs is really helpful.

Honestly, this library deserves more stars than e.g. tflearn or keras!
Now, up to the next 1000 stars 🥇

**Comment by ppwwyyxx** [comment]
Thanks for your help as well! 

I think tflearn and keras are easier to learn and therefore welcomed by a larger community, although they maybe less powerful.
Anyway I'll continue improving it. If it could ever reach a reasonable size of community I will also move it to the organization account from you.

**Comment by Skylion007** [comment]
It really does deserve a ton of stars because it makes Tensorflow actually useful by adding much better support for experimentation. The dataflow and imgaug operators alone make it extremely useful and all the excellently well maintained examples make learning the code base easy. The multiGPU features are absolute icing on the cake and really help on large datasets. Also the documentation, quick bug fixes, and excellent examples are impeccable. 👍

**Comment by vfdev-5** [comment]
Guys, congrats with 2000 stars !
