### ISSUE TITLE
InputDesc Not support tf.SparseTensor

### ISSUE THREAD

**Issue by tonyw** [ppwwyyxx/tensorpack#367]
If I want to define the inputDesc by sparseTensor,How to support it ?

**Comment by ppwwyyxx** [comment]
We had sparse inputdesc support for a while, but later it introduces some issues mainly because not all tensorflow features work for sparse placeholders. We might revisit this feature at some time. 

If my understanding is correct, in tensorflow a sparse tensor is just 3 dense tensors? You can check out [CTC-TIMIT](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/CTC-TIMIT/train-timit.py) example which uses 3 dense InputDesc to get a sparse tensor.

**Comment by tonyw** [comment]
I got it. I will try it.

**Comment by tonyw** [comment]
It's runs ok,thank you for your comments.
