### ISSUE TITLE
tf.float16 support

### ISSUE THREAD

**Issue by yg320** [ppwwyyxx/tensorpack#382]
Hi,

I noticed that tensorpack's layers don't support different types other than float32.
What is the reason for this API limitation? 

Thanks!

**Comment by Skylion007** [comment]
Layers are being deprecated. We are working on replacing them with tf.layers.

**Comment by ppwwyyxx** [comment]
The reason is simply because that's what most people use. The same reason why other wrappers including `tf.layers.conv2d` assumes float32.

For special needs, you don't have to use tensorpack layers. You can wrote symbolic function yourself, or some other wrappers, e.g.:
```python
from tensorflow.python.layers.convolutional import Conv2D
Conv2D(..., dtype=tf.float16)
```

Layers are not being deprecated. #291 is only talking about using `tf.layers` for the implementation of layers.

**Comment by yg320** [comment]
great,

thanks for the quick response!
