### ISSUE TITLE
Augmentor serialization

### ISSUE THREAD

**Issue by vfdev-5** [ppwwyyxx/tensorpack#388]
Hi @ppwwyyxx,

I thought that it could be good to be able to serialize/deserialize data augmentors. For example, such list 
```
augmentors = [
    Resize(shape=(512, 768)),    
    RandomOrderAug([
        Flip(horiz=True, prob=0.5),
        Flip(vert=True, prob=0.5),    
        RandomApplyAug(
                Affine(scale=(0.8, 2.0), 
                       translate_frac=(0.15, 0.15), 
                       rotate_max_deg=45.0, 
                       shear=15.0, 
                       border=cv2.BORDER_REPLICATE, border_value=0.0),
                prob=0.75
        ),        
    ])    
]
```
can be serialized to class name and `self.__dict__` without `rng`:
```
[
   {'config': {'interp': 1, 'shape': (512, 768)}, 'class_name': 'Resize'},
   {'config': {'aug_lists': [
      {'config': {'code': 1, 'prob': 0.5}, 'class_name': 'Flip'}, 
      {'config': {'code': 0, 'prob': 0.5}, 'class_name': 'Flip'}, 
      {'config': {'aug': 
          {'config': 
               {'shear': 15.0, 
                'interp': 1, 
                'border': 1, 
                'rotate_max_deg': 45.0,
                'translate_frac': (0.15, 0.15), 
                'border_value': 0.0, 
                'scale': (0.8, 2.0)}, 
            'class_name': 'Affine'},
          'prob': 0.75}, 
        'class_name': 'RandomApplyAug'}]}, 
   'class_name': 'RandomOrderAug'}
]
```
Is it already possible to serialize/deserialize classes within `tensorpack`?

Serialization is very simple for augmentors and can be done as :
```
def serialize(augmentor):
    return {'class_name': augmentor.__class__.__name__,
            'config': augmentor.get_config()}
```
and `Augmentor` class should have the method:
```
    def get_config(self):
        config = dict(self.__dict__)
        if 'rng' in config:
            del config['rng']
        return config
```
In my fork I try to implement something like [this](https://github.com/ppwwyyxx/tensorpack/compare/master...vfdev-5:master). I will be glab to hear some feedback on this.

Cheers

**Comment by ppwwyyxx** [comment]
Does pickle work? Or do you really want human-readable serialization?
For human-readability you can always just implement __str__ for the augmentors and use pickle + print.

**Comment by vfdev-5** [comment]
I didn't tried pickle mostly because, actually, yes it is better (at least for me) to have human-readable presentation too. My idea behind is to be able to log into a file the whole pipeline used for training/validation and repeat a certain experiment after.

So, yes, I reimplement `__str__` of [`Augmentor`](https://github.com/vfdev-5/tensorpack/blob/master/tensorpack/dataflow/imgaug/base.py#L95) and print parameters without `rng` and any callable. 

I do not quite understand how is done module importing in `dataflow.imgaug` and that's why [`serialize` method code](https://github.com/vfdev-5/tensorpack/blob/master/tensorpack/dataflow/imgaug/base.py#L161) I couldn't put with [`deserialize`](https://github.com/vfdev-5/tensorpack/blob/master/tensorpack/dataflow/imgaug/__init__.py#L36).
And do you plan to cover `imgaug` with tests ?

**Comment by ppwwyyxx** [comment]
Having a human-readable serialization in general is not always a possible thing, because conceptually an augmentor is allowed to contain any object. To repeat an experiment it's better to still use binary format.
Having a serialization which can be transformed into human-readable format is easier, and that's what `__str__` is for. 

Also, for `__repr__`, this is from Python official document:

`object.__repr__(self)`
Called by the repr() built-in function and by string conversions (reverse quotes) to compute the “official” string representation of an object. If at all possible, **this should look like a valid Python expression that could be used to recreate an object with the same value** (given an appropriate environment).

So if `__repr__` is written well, you can get human-readable serialization for most augmentors (actually all existing augmentors) already.

Tests would be nice, of course.. But I myself don't have plans for it now.
