### ISSUE TITLE
allow image augmentations to throw exception

### ISSUE THREAD

**Issue by eyaler** [ppwwyyxx/tensorpack#489]
image augmentations e.g. AugmentImageComponent swallow all non-keyboard exceptions. while they do output a printout, this sometimes goes unnoticed due to later printouts of my program thus effectively failing silently. if this stays the default behaviour i would like an option to override it

**Comment by ppwwyyxx** [comment]
The original idea was to allow some errors to happen occasionally as long as the training is still going, because failing the whole training due to some dirty data can be frustrating.
But I think this is not a good default, due to reasons you mentioned. You can add an option and change the default behavior. Do you want to work on it?

**Comment by ppwwyyxx** [comment]
The current exception handling code piece is repeated for 3 times -- which means it needs to be extracted out to a common function, with an option that disables exception handling.

**Comment by eyaler** [comment]
taking
