### ISSUE TITLE
No GPU version?

### ISSUE THREAD

**Issue by jalfred479** [ppwwyyxx/tensorpack#52]
Is there a version that works without having any GPU?

**Comment by ppwwyyxx** [comment]
This library doesn't require GPUs. 
If you're talking about any specific examples in the project, usually you can just remove `--gpu`.

**Comment by jalfred479** [comment]
Right, I had been using the A3C example in OpenAIGym and hadn't used the `--gpu` argument, but got the following:
`Traceback (most recent call last):
  File "train-atari.py", line 245, in <module>
    nr_gpu = get_nr_gpu()
  File "/home/jalfred/Documents/tensorpack/tensorpack/utils/gpu.py", line 19, in get_nr_gpu
    assert env is not None  # TODO
AssertionError
`

**Comment by ppwwyyxx** [comment]
Yes. a3c didn't support running on CPU. 

The latest commit 6087698d4c8d2e859cbe now added the support . 
i7 skylake is about 50x slower than TitanX.

**Comment by jalfred479** [comment]
I just saw that now, thank you.

**Comment by ppwwyyxx** [comment]
FYI, though it can run on CPU, I found it didn't produce reasonable score.
I guess it's because of the async update issues -- with everything running at slower speed the data I feed may become more outdated and affect training. If I add some random `time.sleep` in the code, even with GPU it learns nothing.
