### ISSUE TITLE
Why tf.crop_and_resize() cannot be RoIAlign?

### ISSUE THREAD

**Issue by insikk** [ppwwyyxx/tensorpack#542]
I read https://github.com/ppwwyyxx/tensorpack/blob/master/examples/FasterRCNN/NOTES.md

You mentioned due to floating point box representation, crop_and_resize cannot be RoI Align.
I don't understand this explanation. Could you enlighten me here?

From this code, I see there is process to generate normalized boxes that is used in tf.crop_and_resize()
https://github.com/ppwwyyxx/tensorpack/blob/6d5ba6a970710eaaa14b89d24aace179eb8ee1af/examples/FasterRCNN/model.py#L316

So my question is if we keep boxes in normalized form at the first place, why tf.crop_and_resize() cannot be RoIAlign?

Honestly, I don't get alignment issue you mentioned here. Maybe this line is the key to help you understand your argument.
> (-0.5 because bilinear sample assumes floating point coordinate (0.0, 0.0) is the same as pixel value (0, 0))

**Comment by ppwwyyxx** [comment]
If you could just simply make a mathematical (rather than conceptual) definition of ROIAlign, it'll be easy to do it correctly then. And it'll be easy to see why some coordinate transform is necessary. It's hard to explain it by words.

The definition would be something like: given an NxN matrix and a bbox (x0,y0,x1,y1) following my definition of bounding box in the notes, get an roi of size kxk, write down the formula for pixel (i, j) in the roi.

**Comment by ppwwyyxx** [comment]
To see the problem with crop_and_resize, try cropping a 4x4 square from a 5x5 square. You may have to try a couple of time to succeed, because it just doesn't behave as what you may expect.

Closing as this is a tensorflow issue.

**Comment by soldierofhell** [comment]
@ppwwyyxx in your NOTES you also mentioned about op written for light-head rcnn:
https://github.com/zengarden/light_head_rcnn/tree/master/lib/lib_kernel/lib_roi_align

Are you planning to add it in near future? And in general are you planning to add their light-head?

**Comment by ppwwyyxx** [comment]
I have no such plans.

**Comment by soldierofhell** [comment]
Ok, so maybe I'll try to do it myself
