### ISSUE TITLE
How to implement a alternating multi-task trainer?

### ISSUE THREAD

**Issue by flyers** [ppwwyyxx/tensorpack#564]
Hi everyone,
Consider the following reinforcement learning scenario where the network architecture consists of a master network and several sub networks. The master network is connected with the sub networks in a specific way. Each of the sub networks corresponds to a specific task. To jointly train both the master network and the sub networks together, the trainer needs to take several different dataflows, possibly at different frequency. In the trainer loop, we then decide which dataflow to use to optimize the corresponding part of the whole network.
The current trainer seems to take only one dataflow. How can I setup such a training pipeline in an easy way?
Thanks very much.

**Comment by ppwwyyxx** [comment]
All built-in trainers are for single-cost optimization task. You need to write your own trainer if you need to alternate between different costs. The tutorial has more details: http://tensorpack.readthedocs.io/en/latest/tutorial/extend/trainer.html ; http://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html

You can also re-formulate your problem to a single-cost optimization one, e.g. by using `tf.cond`. But this may create some overhead.

**Comment by flyers** [comment]
I see. I now understand I have to write my own trainer by inheriting the Trainer class or TowerTrainer class. The [GAN tutorial](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/GAN/GAN.py) is a good example to start with.

There is one thing more. For my case, there are several dataflows instead of one dataflow in the GAN example. Let's say we have two different dataflows d1 and d2. When d1 is fed, it is used to train the sub-network. When d2 is fed, it is used to train the master network. The current example trainer does not show how to get the different dataflows and the corresponding optimizing loss in a train loop.

Could you please provide me some hints on this?

**Comment by ppwwyyxx** [comment]
You can have `InputSource` i1 and i2. Call  `tensors1 = i1.get_input_tensors()` and `tensors2 = i2.get_input_tensors()` respectively to get tensors from the two input source. Then build your graph out of those tensors.

**Comment by ppwwyyxx** [comment]
Also be careful with certain callbacks which evaluate tensors every step. 
For instance, all moving averages summary ops are by default in the same collection (added by the `add_moving_summary` function) and will be run every step (by the `MovingAverageSummary` callback), regardless of which cost you're optimizing. These ops probably depend on your input (e.g., when you're summarizing the output of some layer),  so you may want to disable this callback so that you won't evaluate `inputs2` when optimizing `cost1`.

**Comment by flyers** [comment]
Thanks for your quick reply. I will try to implement this and update this issue for reference when it works.

**Comment by flyers** [comment]
I have some questions for sharing layers with different data batches. Let's say my model looks like follows:
```python
class MyModel(ModelDescBase):
    """ A custom model which consists of two sub-networks on two different tasks with sharing layer"""

    def _get_inputs(self):
    	return [InputDesc(tf.float32, (None, 2), 'input'),
                InputDesc(tf.float32, (None,), 'label'),
                InputDesc(tf.float32, (None, 2), 'input'),
                InputDesc(tf.float32, (None,), 'label'),] 
    
    def _build_graph(self, inputs):
        data1, label1, data2, label2 = inputs
        # sharing layer definition
        
    def _get_optimizer(self):
        lr = tf.get_variable(
            'learning_rate', initializer=1e-4, trainable=False)
        opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
        return opt
```
It takes two different dataflows. So in the build_graph function, the received inputs will be two different data batch. I want to define the graph so that the two networks share common conv or fc layers. It seems that the provide FullyConnected or Conv2D does not support this. How should I achieve this in an elegant way? Does the following code with mixed primitive tf variables work?
```python
def _build_graph(self, inputs):
    data1, label1, data2, label2 = inputs
    # sharing layer definition
    sharing_w = tf.get_variable('w', shape=[2, 10], dtype=tf.float32)

    y1 = tf.nn.relu(tf.matmul(data1, sharing_w))
    y1 = FullyConnected('net1', y1, 1, nl=tf.identity)

    y2 = tf.nn.relu(tf.matmul(data2, sharing_w))
    y2 = FullyConnected('net2', y2, 1, nl=tf.identity)

    y1_loss = tf.nn.l2_loss(y1 - label1, name='net1_loss')
    y2_loss = tf.nn.l2_loss(y2 - label2, name='net2_loss')
```

**Comment by ppwwyyxx** [comment]
`FullyConnected` is merely a symbolic function with `get_variable` inside. To share variables, call `FullyConnected` the second time in a previously-used variable scope with `reuse=True`.

**Comment by flyers** [comment]
I see. That's pretty elegant.

**Comment by flyers** [comment]
I wrote the following simple example where the the trainer is optimizing two sub-networks using two different dataflows. The two dataflows are generated by a separate thread. However, I found that in the training process, the program sometimes get stuck. It seems that the dataflows are blocked. Any idea on why that happens?
```python
import tensorflow as tf
from tensorpack.graph_builder.model_desc import ModelDescBase, InputDesc
from tensorpack import FullyConnected, BatchData, DataFromQueue, StartProcOrThread, FeedInput, ModelSaver
# from tensorpack.train.base import Trainer
from tensorpack.train.tower import TowerTrainer
from tensorpack.tfutils import optimizer, summary
from tensorpack.tfutils.tower import TowerContext, TowerFuncWrapper, get_current_tower_context
from tensorpack.utils.argtools import memoized
from tensorpack.utils import logger
import threading
from six.moves import queue
import numpy as np


class MyModel(ModelDescBase):
    """ A custom model which consists of two sub-networks"""

    def _get_inputs(self):
        l = self.get_inputs_desc_list()
        res = []
        for x in l:
            res += x
        return res

    def get_inputs_desc_list(self):
        ds1 = [InputDesc(tf.float32, (None, 2), 'input'),
               InputDesc(tf.float32, (None,), 'label')]
        ds2 = [InputDesc(tf.float32, (None, 2), 'input'),
               InputDesc(tf.float32, (None,), 'label')]
        return [ds1, ds2]

    def _build_graph(self, inputs):
        data1, label1, data2, label2 = inputs
        with tf.variable_scope("share") as share_scope:
            y1 = FullyConnected('fc0', data1, 10, nl=tf.nn.relu)

        with tf.variable_scope('net1'):
            y1 = FullyConnected('fc_out', y1, 1, nl=tf.identity)

        with tf.variable_scope('net2'):
            with tf.variable_scope(share_scope, reuse=True):
                y2 = FullyConnected('fc0', data2, 10, nl=tf.nn.relu)
            y2 = FullyConnected('fc_out', y2, 1, nl=tf.identity)

        self.y1_loss = tf.nn.l2_loss(y1 - label1)
        self.y1_loss = tf.truediv(self.y1_loss, tf.cast(
            tf.shape(label1)[0], tf.float32), name='net1_loss')
        self.y2_loss = tf.nn.l2_loss(y2 - label2)
        self.y2_loss = tf.truediv(self.y2_loss, tf.cast(
            tf.shape(label2)[0], tf.float32), name='net2_loss')

        self.vars1 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'share') + \
            tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net1')
        self.vars2 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'share') + \
            tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net2')

        summary.add_moving_summary(self.y1_loss, self.y2_loss)

    @memoized
    def get_optimizer(self):
        lr = tf.get_variable(
            'learning_rate', initializer=1e-4, trainable=False)
        opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
        return opt


class MyTrainer(TowerTrainer):
    """
    A custom trainer which optimize several costs from different dataflows simutaneously
    """

    def __init__(self, inputs, model):
        """
        inputs ([InputSource]): a list of several InputSources
        model (ModelDescBase): a model
        """
        super(MyTrainer, self).__init__()
        inputs_desc = model.get_inputs_desc()
        inputs_desc_list = model.get_inputs_desc_list()

        # setup input callbacks for each InputSource
        for dataflow, desc in zip(inputs, inputs_desc_list):
            cbs = dataflow.setup(desc)
            self.register_callback(cbs)

        # build the graph
        self.tower_func = TowerFuncWrapper(model.build_graph, inputs_desc)
        tensors = []
        for dataflow in inputs:
            tensors += dataflow.get_input_tensors()
        with TowerContext('', is_training=True):
            self.tower_func(*tensors)

        opt = model.get_optimizer()
        with tf.name_scope('optimize'):
            self.opt_y1 = opt.minimize(
                model.y1_loss, var_list=model.vars1, name='op1')
            self.opt_y2 = opt.minimize(
                model.y2_loss, var_list=model.vars2, name='op2')

    def run_step(self):
        self.hooked_sess.run(self.opt_y1)
        self.hooked_sess.run(self.opt_y2)


class DataThread(threading.Thread):
    """
    A thread to generate data for different dataflows
    """

    def __init__(self, batch_size):
        super(DataThread, self).__init__()
        self.queue1 = queue.Queue(maxsize=batch_size * 8 * 2)
        self.queue2 = queue.Queue(maxsize=batch_size * 8 * 2)

        self.daemon = True
        self.name = 'DataThread'

    def run(self):
        while True:
            if np.random.rand() < 0.5:
                x = np.random.rand(2)
                y = np.sum(x * x)
                self.queue1.put([x, y])
            else:
                x = np.random.rand(2)
                y = np.sum(x * x) * 0.001
                self.queue2.put([x, y])


if __name__ == '__main__':
    # logger.set_logger_dir('/home/sliay/models/trainer')
    BATCH_SIZE = 128
    data_gen = DataThread(BATCH_SIZE)
    data1 = BatchData(DataFromQueue(data_gen.queue1), BATCH_SIZE)
    data2 = BatchData(DataFromQueue(data_gen.queue2), BATCH_SIZE)
    M = MyModel()
    MyTrainer([FeedInput(data1), FeedInput(data2)], M).train_with_defaults(
        callbacks=[StartProcOrThread(data_gen),
                   ],
        steps_per_epoch=100,
        max_epoch=100,
    )

```

**Comment by ppwwyyxx** [comment]
Thanks for the code. It's very helpful to have runnable code for debugging.

`queue.put` will block when a queue reaches its max size. When you are unlucky: one queue reaches max size and the other queue is empty, the whole thread blocks. 
You can proof that the expected time it happens is (maxsize)^2.

**Comment by ppwwyyxx** [comment]
Some other notes:
```
        for dataflow, desc in zip(inputs, inputs_desc_list):
            cbs = dataflow.setup(desc)
            self.register_callback(cbs)
```
Because of this, every `hooked_sess.run` will feed both data to the graph, though only part of them will not be used for training. This is because data feeding is performed through callbacks. You can use `QueueInput` instead which doesn't feed anything.

`summary.add_moving_summary(self.y1_loss, self.y2_loss)`
I mentioned earlier about summaries. This will let `hooked_sess.run` to evaluated both loss every time, though only one of them will be used for training. This function allows you to use a different collection name which can avoid this issue.

These are only performance-related, though. Shouldn't affect the correctness of your code.

**Comment by flyers** [comment]
1. Thanks for your explanation. So if I have a master thread which maintains several queues, I can increase the maxsize to reduce the probability it is blocked.
2. As for the data feeding process, my current implementation will waste some data which will not be used for training. Is my understanding correct? That's not what I want. Can I avoid this by using QueueInput instead of FeedInput?
3. I did not get how to use different collection name for this. Will the following do or I also need to modify the other part?
```python
summary.add_moving_summary(self.y1_loss, collection='loss1')
summary.add_moving_summary(self.y2_loss, collection='loss2')
```

**Comment by flyers** [comment]
I also have another question in case of creating predictors in `TowerTrainer`. In my case I want to create different predictors for evaluating `y1` and `y2` separately. Do I need to create several different `tower_func` or I just need to call `SimplePredictBuilder` with different names?

**Comment by ppwwyyxx** [comment]
1. you can have two threads for both data so they will not be blocked
2. correct. QueueInput will avoid this.
3. yes it will use a different collection name. then you'll need to get the ops from the collection and eval them together with the corresponding `hooked_sess.run`.

`SimplePredictBuilder` simply calls your `build_graph`. So it should be fine. In fact the existing `trainer.get_predictor` should work for your case.

**Comment by flyers** [comment]
I have updated the code to address the above three issues. It seems that they are all solved. However, when I tried to create separate online predictors in the trainer, some error happens. The following is my code. It seems that the tower function is having issues finding the tensor in the graph.
```python
import tensorflow as tf
from tensorpack import ModelDescBase, InputDesc, FullyConnected, \
    BatchData, DataFromQueue, StartProcOrThread, QueueInput, ModelSaver, PeriodicTrigger
from tensorpack.callbacks import Callback
# from tensorpack.train.base import Trainer
from tensorpack.train.tower import TowerTrainer
from tensorpack.tfutils import optimizer, summary
from tensorpack.tfutils.tower import TowerContext, TowerFuncWrapper, get_current_tower_context
from tensorpack.utils.argtools import memoized
from tensorpack.utils import logger
import threading
from six.moves import queue
import numpy as np


class MyModel(ModelDescBase):
    """ A custom model which consists of two sub-networks"""

    def _get_inputs(self):
        l = self.get_inputs_desc_list()
        res = []
        for x in l:
            res += x
        return res

    def get_inputs_desc_list(self):
        ds1 = [InputDesc(tf.float32, (None, 2), 'input'),
               InputDesc(tf.float32, (None,), 'label')]
        ds2 = [InputDesc(tf.float32, (None, 2), 'input'),
               InputDesc(tf.float32, (None,), 'label')]
        return [ds1, ds2]

    def _build_graph(self, inputs):
        data1, label1, data2, label2 = inputs
        with tf.variable_scope("share") as share_scope:
            y1 = FullyConnected('fc0', data1, 10, nl=tf.nn.relu)

        with tf.variable_scope('net1'):
            y1 = FullyConnected('fc_out', y1, 1, nl=tf.identity)

        with tf.variable_scope('net2'):
            with tf.variable_scope(share_scope, reuse=True):
                y2 = FullyConnected('fc0', data2, 10, nl=tf.nn.relu)
            y2 = FullyConnected('fc_out', y2, 1, nl=tf.identity)

        self.y1_loss = tf.nn.l2_loss(y1 - label1)
        self.y1_loss = tf.truediv(self.y1_loss, tf.cast(
            tf.shape(label1)[0], tf.float32), name='net1_loss')
        self.y2_loss = tf.nn.l2_loss(y2 - label2)
        self.y2_loss = tf.truediv(self.y2_loss, tf.cast(
            tf.shape(label2)[0], tf.float32), name='net2_loss')

        self.vars1 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'share') + \
            tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net1')
        self.vars2 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'share') + \
            tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net2')

        summary.add_moving_summary(self.y1_loss, collection='loss1')
        summary.add_moving_summary(self.y2_loss, collection='loss2')

    @memoized
    def get_optimizer(self):
        lr = tf.get_variable(
            'learning_rate', initializer=1e-4, trainable=False)
        opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
        return opt


class MyTrainer(TowerTrainer):
    """
    A custom trainer which optimize several costs from different dataflows simutaneously
    """

    def __init__(self, inputs, model):
        """
        inputs ([InputSource]): a list of several InputSources
        model (ModelDescBase): a model
        """
        super(MyTrainer, self).__init__()
        inputs_desc = model.get_inputs_desc()
        inputs_desc_list = model.get_inputs_desc_list()

        # setup input callbacks for each InputSource
        for dataflow, desc in zip(inputs, inputs_desc_list):
            cbs = dataflow.setup(desc)
            self.register_callback(cbs)

        # build the graph
        self.tower_func = TowerFuncWrapper(model.build_graph, inputs_desc)
        tensors = []
        for dataflow in inputs:
            tensors += dataflow.get_input_tensors()
        with TowerContext('', is_training=True):
            self.tower_func(*tensors)

        opt = model.get_optimizer()
        with tf.name_scope('optimize'):
            self.opt_y1 = opt.minimize(
                model.y1_loss, var_list=model.vars1, name='op1')
            self.opt_y2 = opt.minimize(
                model.y2_loss, var_list=model.vars2, name='op2')

    def run_step(self):
        self.hooked_sess.run([self.opt_y1, tf.get_collection('loss1')])
        self.hooked_sess.run([self.opt_y2, tf.get_collection('loss2')])

    def get_predictor1(self):
        return self.get_predictor(['input'], ['net1/fc_out'])

    def get_predictor2(self):
        return self.get_predictor(['input'], ['net2/fc_out'])


class DataThread1(threading.Thread):
    def __init__(self, batch_size):
        super(DataThread1, self).__init__()
        self.queue = queue.Queue(maxsize=batch_size * 8 * 2)
        self.daemon = True
        self.name = 'DataThread1'

    def run(self):
        while True:
            x = np.random.rand(2)
            y = np.sum(x * x)
            self.queue.put([x, y])


class DataThread2(threading.Thread):
    def __init__(self, batch_size):
        super(DataThread2, self).__init__()
        self.queue = queue.Queue(maxsize=batch_size * 8 * 2)
        self.daemon = True
        self.name = 'DataThread2'

    def run(self):
        while True:
            x = np.random.rand(2)
            y = np.sum(x * x) * 0.001
            self.queue.put([x, y])


class Evaluator(Callback):
    def _setup_graph(self):
        self.pred_func = self.trainer.get_predictor1()

    def _trigger(self):
        x = np.array([1, 2])
        pred = self.pred_func(x[None])[0][0]
        self.trainer.monitors.put_scalar('pred', pred)

if __name__ == '__main__':
    logger.set_logger_dir('/home/sliay/models/trainer')
    BATCH_SIZE = 128
    data_gen1 = DataThread1(BATCH_SIZE)
    data_gen2 = DataThread2(BATCH_SIZE)
    data1 = BatchData(DataFromQueue(data_gen1.queue), BATCH_SIZE)
    data2 = BatchData(DataFromQueue(data_gen2.queue), BATCH_SIZE)
    M = MyModel()
    MyTrainer([QueueInput(data1), QueueInput(data2)], M).train_with_defaults(
        callbacks=[
            StartProcOrThread(data_gen1),
            StartProcOrThread(data_gen2),
            PeriodicTrigger(Evaluator(),
                every_k_epochs=1),
        ],
        steps_per_epoch=100,
        max_epoch=100,
    )

```

**Comment by ppwwyyxx** [comment]
`net1/fc1_out` is the name scope of the fc layer. The tensor name is actually `net1/fc_out/output` if you print it. The documentation only vaguely mentions this. I'll add some more.

Also you have conflicting names in inputsdesc, so it's ambiguous when you do `get_predictor`. I should make it raise an error.

**Comment by flyers** [comment]
Thanks very much for your help. I will paste my final runnable code here in case anyone else want to do similar thing such as multitask training.
```python
import tensorflow as tf
from tensorpack import ModelDescBase, InputDesc, FullyConnected, \
    BatchData, DataFromQueue, StartProcOrThread, QueueInput, ModelSaver, PeriodicTrigger
from tensorpack.callbacks import Callback
from tensorpack.train.tower import TowerTrainer
from tensorpack.tfutils import optimizer, summary
from tensorpack.tfutils.tower import TowerContext, TowerFuncWrapper, get_current_tower_context
from tensorpack.utils.argtools import memoized
from tensorpack.utils import logger
import threading
from six.moves import queue
import numpy as np


class MyModel(ModelDescBase):
    """ A custom model which consists of two sub-networks"""

    def _get_inputs(self):
        l = self.get_inputs_desc_list()
        res = []
        for x in l:
            res += x
        return res

    def get_inputs_desc_list(self):
        ds1 = [InputDesc(tf.float32, (None, 2), 'input1'),
               InputDesc(tf.float32, (None,), 'label1')]
        ds2 = [InputDesc(tf.float32, (None, 2), 'input2'),
               InputDesc(tf.float32, (None,), 'label2')]
        return [ds1, ds2]

    def _build_graph(self, inputs):
        data1, label1, data2, label2 = inputs
        with tf.variable_scope("share") as share_scope:
            y1 = FullyConnected('fc0', data1, 10, nl=tf.nn.relu)

        with tf.variable_scope('net1'):
            y1 = FullyConnected('fc_out', y1, 1, nl=tf.identity)

        with tf.variable_scope('net2'):
            with tf.variable_scope(share_scope, reuse=True):
                y2 = FullyConnected('fc0', data2, 10, nl=tf.nn.relu)
            y2 = FullyConnected('fc_out', y2, 1, nl=tf.identity)

        self.y1_loss = tf.nn.l2_loss(y1 - label1)
        self.y1_loss = tf.truediv(self.y1_loss, tf.cast(
            tf.shape(label1)[0], tf.float32), name='net1_loss')
        self.y2_loss = tf.nn.l2_loss(y2 - label2)
        self.y2_loss = tf.truediv(self.y2_loss, tf.cast(
            tf.shape(label2)[0], tf.float32), name='net2_loss')

        self.vars1 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'share') + \
            tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net1')
        self.vars2 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'share') + \
            tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net2')

        summary.add_moving_summary(self.y1_loss, collection='loss1')
        summary.add_moving_summary(self.y2_loss, collection='loss2')

    @memoized
    def get_optimizer(self):
        lr = tf.get_variable(
            'learning_rate', initializer=1e-4, trainable=False)
        opt = tf.train.AdamOptimizer(lr, epsilon=1e-3)
        return opt


class MyTrainer(TowerTrainer):
    """
    A custom trainer which optimize several costs from different dataflows simutaneously
    """

    def __init__(self, inputs, model):
        """
        inputs ([InputSource]): a list of several InputSources
        model (ModelDescBase): a model
        """
        super(MyTrainer, self).__init__()
        inputs_desc = model.get_inputs_desc()
        inputs_desc_list = model.get_inputs_desc_list()

        # setup input callbacks for each InputSource
        for dataflow, desc in zip(inputs, inputs_desc_list):
            cbs = dataflow.setup(desc)
            self.register_callback(cbs)

        # build the graph
        self.tower_func = TowerFuncWrapper(model.build_graph, inputs_desc)
        tensors = []
        for dataflow in inputs:
            tensors += dataflow.get_input_tensors()
        with TowerContext('', is_training=True):
            self.tower_func(*tensors)

        opt = model.get_optimizer()
        with tf.name_scope('optimize'):
            self.opt_y1 = opt.minimize(
                model.y1_loss, var_list=model.vars1, name='op1')
            self.opt_y2 = opt.minimize(
                model.y2_loss, var_list=model.vars2, name='op2')

    def run_step(self):
        self.hooked_sess.run([self.opt_y1, tf.get_collection('loss1')])
        self.hooked_sess.run([self.opt_y2, tf.get_collection('loss2')])

    def get_predictor1(self):
        return self.get_predictor(['input1'], ['net1/fc_out/output'])

    def get_predictor2(self):
        return self.get_predictor(['input2'], ['net2/fc_out/output'])


class DataThread1(threading.Thread):
    def __init__(self, batch_size):
        super(DataThread1, self).__init__()
        self.queue = queue.Queue(maxsize=batch_size * 8 * 2)
        self.daemon = True
        self.name = 'DataThread1'

    def run(self):
        while True:
            x = np.random.rand(2)
            y = np.sum(x)
            self.queue.put([x, y])


class DataThread2(threading.Thread):
    def __init__(self, batch_size):
        super(DataThread2, self).__init__()
        self.queue = queue.Queue(maxsize=batch_size * 8 * 2)
        self.daemon = True
        self.name = 'DataThread2'

    def run(self):
        while True:
            x = np.random.rand(2)
            y = np.sum(x) * 0.01
            self.queue.put([x, y])


class Evaluator(Callback):
    def _setup_graph(self):
        self.pred_func1 = self.trainer.get_predictor1()
        self.pred_func2 = self.trainer.get_predictor2()

    def _trigger(self):
        x = np.array([1, 2])
        pred1 = self.pred_func1(x[None])[0][0]
        pred2 = self.pred_func2(x[None])[0][0]
        self.trainer.monitors.put_scalar('pred1', np.asscalar(pred1))
        self.trainer.monitors.put_scalar('pred2', np.asscalar(pred2))

if __name__ == '__main__':
    logger.set_logger_dir('/home/sliay/models/trainer')
    BATCH_SIZE = 128
    data_gen1 = DataThread1(BATCH_SIZE)
    data_gen2 = DataThread2(BATCH_SIZE)
    data1 = BatchData(DataFromQueue(data_gen1.queue), BATCH_SIZE)
    data2 = BatchData(DataFromQueue(data_gen2.queue), BATCH_SIZE)
    M = MyModel()
    MyTrainer([QueueInput(data1), QueueInput(data2)], M).train_with_defaults(
        callbacks=[
            StartProcOrThread(data_gen1),
            StartProcOrThread(data_gen2),
            PeriodicTrigger(Evaluator(),
                every_k_epochs=1),
        ],
        steps_per_epoch=100,
        max_epoch=100,
    )
```

**Comment by mikeun** [comment]
Hi,
I'd like to implement NN model with two cost functions.
First network will classify input data - tune all weights (W) by minimizing weighted logloss.
Second part will take some of these weights (W), apply linear algebra functions and minimize result (L2 or L1 loss). Second part should work on the (W) also.
What kind of approach (your examples) will you recommend?

**Comment by ppwwyyxx** [comment]
You can either try to formulate the problem to a single-cost optimization problem with `tf.cond` or `tf.control_dependencies`. If this is not possible, you can define the training step yourself, like the GAN trainer examples or the code above.

**Comment by sgzqc** [comment]
Hi all, i want to do the multi-task training like above, but i would like to read image from filefolder. So how can we realize run function in DataThread class like above? And i often do this by DatafromList.

    def run(self):
        while True:
            x = np.random.rand(2)
            y = np.sum(x)
            self.queue.put([x, y])


`

**Comment by sgzqc** [comment]
Hi all, i have run the example code above, the result is not normal just because the QueueInput/queue_size has data while the QueueInput_1/queue_size is almost empty, the log is as below:
[0717 18:49:04 @base.py:272] Epoch 90 (global_step 18000) finished, time:1.47 seconds.
[0717 18:49:05 @monitor.py:428] QueueInput/queue_size: 34.267
[0717 18:49:05 @monitor.py:428] QueueInput_1/queue_size: 1.5595e-38
[0717 18:49:05 @monitor.py:428] net1_loss: 10.731
[0717 18:49:05 @monitor.py:428] net2_loss: 0.004886
[0717 18:49:05 @monitor.py:428] pred1: 0.94957
[0717 18:49:05 @monitor.py:428] pred2: 0.015798
[0717 18:49:05 @base.py:262] Start Epoch 91 ...
100%|##########|100/100[00:01<00:00,63.74it/s]
[0717 18:49:06 @base.py:272] Epoch 91 (global_step 18200) finished, time:1.57 seconds.
[0717 18:49:06 @monitor.py:428] QueueInput/queue_size: 35.001
[0717 18:49:06 @monitor.py:428] QueueInput_1/queue_size: 1.5303e-38
[0717 18:49:06 @monitor.py:428] net1_loss: 10.888
[0717 18:49:06 @monitor.py:428] net2_loss: 0.0055581
[0717 18:49:06 @monitor.py:428] pred1: 0.95158
[0717 18:49:06 @monitor.py:428] pred2: 0.0138
[0717 18:49:06 @base.py:262] Start Epoch 92 ...
100%|##########|100/100[00:01<00:00,68.13it/s]
[0717 18:49:08 @base.py:272] Epoch 92 (global_step 18400) finished, time:1.47 seconds.
[0717 18:49:08 @monitor.py:428] QueueInput/queue_size: 34.065
[0717 18:49:08 @monitor.py:428] QueueInput_1/queue_size: 1.4937e-38
[0717 18:49:08 @monitor.py:428] net1_loss: 10.866
[0717 18:49:08 @monitor.py:428] net2_loss: 0.0048307
[0717 18:49:08 @monitor.py:428] pred1: 0.92544
[0717 18:49:08 @monitor.py:428] pred2: 0.015397
[0717 18:49:08 @base.py:262] Start Epoch 93 ...
100%|##########|100/100[00:01<00:00,63.75it/s]
[0717 18:49:09 @base.py:272] Epoch 93 (global_step 18600) finished, time:1.57 seconds.
[0717 18:49:09 @monitor.py:428] QueueInput/queue_size: 38.195
[0717 18:49:09 @monitor.py:428] QueueInput_1/queue_size: 1.42e-38
[0717 18:49:09 @monitor.py:428] net1_loss: 10.45
[0717 18:49:09 @monitor.py:428] net2_loss: 0.0047563
[0717 18:49:09 @monitor.py:428] pred1: 0.94389
[0717 18:49:09 @monitor.py:428] pred2: 0.014586
[0717 18:49:09 @base.py:262] Start Epoch 94 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:11 @base.py:272] Epoch 94 (global_step 18800) finished, time:1.57 seconds.
100%|##########|100/100[00:01<00:00,63.74it/s]
[0717 18:49:11 @monitor.py:428] QueueInput/queue_size: 36.5
[0717 18:49:11 @monitor.py:428] QueueInput_1/queue_size: 1.5501e-38
[0717 18:49:11 @monitor.py:428] net1_loss: 10.427
[0717 18:49:11 @monitor.py:428] net2_loss: 0.004415
[0717 18:49:11 @monitor.py:428] pred1: 0.95424
[0717 18:49:11 @monitor.py:428] pred2: 0.014196
[0717 18:49:11 @base.py:262] Start Epoch 95 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:13 @base.py:272] Epoch 95 (global_step 19000) finished, time:1.47 seconds.
100%|##########|100/100[00:01<00:00,68.15it/s]
[0717 18:49:13 @monitor.py:428] QueueInput/queue_size: 39.004
[0717 18:49:13 @monitor.py:428] QueueInput_1/queue_size: 1.2729e-38
[0717 18:49:13 @monitor.py:428] net1_loss: 10.679
[0717 18:49:13 @monitor.py:428] net2_loss: 0.004388
[0717 18:49:13 @monitor.py:428] pred1: 0.94648
[0717 18:49:13 @monitor.py:428] pred2: 0.014553
[0717 18:49:13 @base.py:262] Start Epoch 96 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:14 @base.py:272] Epoch 96 (global_step 19200) finished, time:1.47 seconds.
100%|##########|100/100[00:01<00:00,68.10it/s]
[0717 18:49:14 @monitor.py:428] QueueInput/queue_size: 43.999
[0717 18:49:14 @monitor.py:428] QueueInput_1/queue_size: 1.5625e-38
[0717 18:49:14 @monitor.py:428] net1_loss: 10.688
[0717 18:49:14 @monitor.py:428] net2_loss: 0.0045032
[0717 18:49:14 @monitor.py:428] pred1: 0.95173
[0717 18:49:14 @monitor.py:428] pred2: 0.013164
[0717 18:49:14 @base.py:262] Start Epoch 97 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:16 @base.py:272] Epoch 97 (global_step 19400) finished, time:1.47 seconds.
100%|##########|100/100[00:01<00:00,68.08it/s]
[0717 18:49:16 @monitor.py:428] QueueInput/queue_size: 46.185
[0717 18:49:16 @monitor.py:428] QueueInput_1/queue_size: 2.1594e-38
[0717 18:49:16 @monitor.py:428] net1_loss: 10.591
[0717 18:49:16 @monitor.py:428] net2_loss: 0.0041702
[0717 18:49:16 @monitor.py:428] pred1: 0.93017
[0717 18:49:16 @monitor.py:428] pred2: 0.012632
[0717 18:49:16 @base.py:262] Start Epoch 98 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:17 @base.py:272] Epoch 98 (global_step 19600) finished, time:1.52 seconds.
100%|##########|100/100[00:01<00:00,65.84it/s]
[0717 18:49:17 @monitor.py:428] QueueInput/queue_size: 46.516
[0717 18:49:17 @monitor.py:428] QueueInput_1/queue_size: 1.6361e-38
[0717 18:49:17 @monitor.py:428] net1_loss: 10.789
[0717 18:49:17 @monitor.py:428] net2_loss: 0.0041644
[0717 18:49:17 @monitor.py:428] pred1: 0.95202
[0717 18:49:17 @monitor.py:428] pred2: 0.01548
[0717 18:49:17 @base.py:262] Start Epoch 99 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:19 @base.py:272] Epoch 99 (global_step 19800) finished, time:1.52 seconds.
100%|##########|100/100[00:01<00:00,65.88it/s]
[0717 18:49:19 @monitor.py:428] QueueInput/queue_size: 48.972
[0717 18:49:19 @monitor.py:428] QueueInput_1/queue_size: 1.5584e-38
[0717 18:49:19 @monitor.py:428] net1_loss: 11.04
[0717 18:49:19 @monitor.py:428] net2_loss: 0.0040718
[0717 18:49:19 @monitor.py:428] pred1: 0.96595
[0717 18:49:19 @monitor.py:428] pred2: 0.015411
[0717 18:49:19 @base.py:262] Start Epoch 100 ...
  0%|          |0/100[00:00<?,?it/s][0717 18:49:21 @base.py:272] Epoch 100 (global_step 20000) finished, time:1.47 seconds.
100%|##########|100/100[00:01<00:00,68.09it/s]
[0717 18:49:21 @monitor.py:428] QueueInput/queue_size: 50
[0717 18:49:21 @monitor.py:428] QueueInput_1/queue_size: 1.5499e-38
[0717 18:49:21 @monitor.py:428] net1_loss: 10.796
[0717 18:49:21 @monitor.py:428] net2_loss: 0.0042789
[0717 18:49:21 @monitor.py:428] pred1: 0.96815
[0717 18:49:21 @monitor.py:428] pred2: 0.015265
[0717 18:49:21 @base.py:276] Training has finished!
[0717 18:49:21 @input_source.py:149] EnqueueThread QueueInput/input_queue Exited.
2018-07-17 18:49:21.051904: W tensorflow/core/kernels/queue_base.cc:295] _1_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed


Anyone can give me some suggest ?
