### ISSUE TITLE
something about bit convolution kernel

### ISSUE THREAD

**Issue by Paseam** [ppwwyyxx/tensorpack#66]
hi, i think the bit convolution kernel is the key to accelerate the network, but if i do as your paper say, more time will be need, can you give me some tips about your way to implement bit convolution kernel ? thanks

**Comment by ppwwyyxx** [comment]
Sorry but we're not going to release the implementation in very detail. But in general you wouldn't see bad performance as long as data is loaded in a cache-friendly way and all computation is performed in SIMD instructions.
This issue is not very related to tensorpack so I'm closing it for now. If you have questions about the paper please write to the authors.

**Comment by deepsemantic** [comment]
Hi @Paseam, happy to hearing that you are implementing bit convolution kernel, I am also implementing it with same problem as your----too slow for training, could you give me some hints that how you did the implementation. Thanks in advance.
