### ISSUE TITLE
Can tensorpack build a new graph in Model class?

### ISSUE THREAD

**Issue by whj363636** [ppwwyyxx/tensorpack#738]
In fact, I would like to use _tf.contrib.factorization.KMeans_ in my Model class, more specifically, before(or after, it doesn't matter) some convolution layer or FC layer, like https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/factorization/examples/mnist.py

But _tf.contrib.factorization.KMeans_ need generating KMeans clustering graph. So when I build kmeans graph by calling _kmeans.training_graph()_ in the Model, I get error as below:

> tensorpack/graph_builder/utils.py", line 82, in __call__
    self.ps_sizes[device_index] += var_size
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

I wonder how to solve it in a tensorpack way? Thanks

**Comment by ppwwyyxx** [comment]
Could you please post full error?

**Comment by ppwwyyxx** [comment]
Looks like there are a couple of problems with this kmeans.

First of all it creates trainable variables of unknown shape. Some of the utilities in tensorpack assume variables have fully defined shape. The above commit should help with that.
Secondly it does not respect variable reuse. It creates variables even under a "reuse=True" variable scope, which means you cannot use it with tensorpack [TowerTrainer](http://tensorpack.readthedocs.io/en/latest/tutorial/trainer.html#tower-trainer) and all its subclasses.

Thirdly it is not trained by gradient descent, although it creates trainable variables. This means you cannot train it with tensorpack [ModelDesc](http://tensorpack.readthedocs.io/en/latest/tutorial/training-interface.html#with-modeldesc-and-trainconfig) which assumes single-cost gradient-based optimization.

To use kmeans you'll probably need to build your graph manually and [write your own trainer](http://tensorpack.readthedocs.io/en/latest/tutorial/extend/trainer.html). I don't know if there are other ways around because I'm not familiar with the kmeans module.

**Comment by whj363636** [comment]
I will try. Thanks very much for your help.
