### ISSUE TITLE
multigpu training

### ISSUE THREAD

**Issue by yzpick** [ppwwyyxx/tensorpack#748]
Hi, I am using multigpu training and got those warning messages:
syncmultigpureplicatedbuilder variable has prefix tower0, this is unexpected
replicatedtrainer, cannot find ... in graph

And those "cannot find variables" are only bidirectional(from rnn) variables.

I can still do the training, but do those warning messages matter?

Thanks!

**Comment by ppwwyyxx** [comment]
Please paste your logs instead of describing them.

**Comment by yzpick** [comment]
xxxxxxxxxxxxxx
[0504 13:37:58 @training.py:100] Building graph for training tower 1 on device /gpu:1 ...
xxxxxxxxxxxxxxx
[0504 13:39:42 @training.py:100] Building graph for training tower 2 on device /gpu:2 ...
xxxxxxxxxxxxxxx
[0504 13:42:36 @training.py:284] WRN [SyncMultiGPUReplicatedBuilder] variable tower0/bidirectional/Variable:0 has prefix 'tower0', this is unexpected.
xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[0504 13:42:36 @training.py:284] WRN [SyncMultiGPUReplicatedBuilder] variable tower0/bidirectional/Variable/Adam:0 has prefix 'tower0', this is unexpected.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[0504 13:42:36 @training.py:297] WRN [ReplicatedTrainer] Cannot find bidirectional/conv_lst_m2d_16/kernel:0 in the graph!
[0504 13:42:36 @training.py:297] WRN [ReplicatedTrainer] Cannot find bidirectional/conv_lst_m2d_16/recurrent_kernel:0 in the graph!
xxxxxxxxxxxxxxxxxxxxxxxx
[0504 13:42:36 @training.py:299] 'sync_variables_from_main_tower' includes 606 operations.

i use xxxxxxxxxxx to replace similar messages

**Comment by ppwwyyxx** [comment]
Are you using some functions from tensorflow to create these bidirectional rnn variables or are you creating them with your own symbolic code?

**Comment by yzpick** [comment]
i am using Keras, it is the bidirectional layer wrapper: https://keras.io/layers/wrappers/

**Comment by ppwwyyxx** [comment]
It's best if you could __paste__ some relevant code. They're always more helpful than words. Now it looks like some Keras layers create variables in a way incompatible with tensorpack's multigpu trainers. There may be solutions but I don't know how to reproduce such error now.

Also, full logs are more helpful than xxxxxx. If you prefer you can use 

```
<details>
<summary>Click to expand</summary>
logs
</details>
```
so that they don't take too much space.

**Comment by yzpick** [comment]
I checked a bit, it looks like it is not the bidirectional wrapper that has problem, it is the convlstm2d layer in keras, i am not sure if you can reproduce the error using this one https://github.com/keras-team/keras/blob/master/examples/conv_lstm.py

**Comment by ppwwyyxx** [comment]
The problem comes from the following code in ConvRNN2D:
```
  def get_initial_state(self, inputs):
    # (samples, timesteps, rows, cols, filters)
    initial_state = K.zeros_like(inputs)
    # (samples, rows, cols, filters)
    initial_state = K.sum(initial_state, axis=1)
    shape = list(self.cell.kernel_shape)
    shape[-1] = self.cell.filters
    initial_state = self.cell.input_conv(initial_state,
                                         K.zeros(tuple(shape)),
                                         padding=self.cell.padding)

    if hasattr(self.cell.state_size, '__len__'):
      return [initial_state for _ in self.cell.state_size]
    else:
      return [initial_state]
```
It calls `K.zeros`, which in my test case creates a all-zero VARIABLE
instead of a all-zero constant TENSOR.

This abuse of variables by itself looks like a bad choice because it hurt
performance and memory.

It does not create this variable with the variable scope name, but still
put the the variable into TRAINABLE_VARIABLES collection, which breaks a
lot of contract of a "tower function". Therefore such symbolic functions
cannot be used with tensorpack.

**Comment by ppwwyyxx** [comment]
In the Conv2DLSTM case I think it happens to do the correct thing. Because tensorpack trainer just ignores this variable. But I'm not totally sure.

**Comment by ppwwyyxx** [comment]
I'll take a look later. Maybe there are ways to handle this better.

**Comment by yzpick** [comment]
Sure. Have a nice weekend :)

**Comment by ppwwyyxx** [comment]
Some checks were added to fix the collection after calling Keras models. Variables are now marked trainable iff it was marked trainable by Keras AND it appears in Keras's `model.weights`. This seems to make ConvLSTM work and produce a more reasonable warning.
