### ISSUE TITLE
roi_align: Default AvgPoolingOp only supports NHWC

### ISSUE THREAD

**Issue by Superlee506** [ppwwyyxx/tensorpack#753]
Python version: 3.5
TF version: 1.4.0
Tensorpack version: 0.8.5
Ubuntu 16.04 + CUDA 8.0 + cudnn6.0

When I tested the "roi_align" function in Faster RCNN examples,  I get following error message as follows:

```
2018-05-08 19:14:03.427472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:85:00.0, compute capability: 3.7)
2018-05-08 19:14:03.637287: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC.
	 [[Node: roi_align/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:GPU:0"](roi_align/crop_and_resize/transpose_1)]]
```

I have checked the same issue as #263 , and I know this error will occur when using CPU, but I used GPU here.
My testing codes are as follows:

![image](https://user-images.githubusercontent.com/13114675/39787563-f05fb0ec-52f3-11e8-9b0b-fd8ea0c16728.png)

**Comment by ppwwyyxx** [comment]
You didn't paste the full log.

The sess.run actually succeeded, otherwise it's a tensorflow bug. You can ignore the error and still get the output. And in an actual training you'll not see such an error.
The error comes because you use a constant as input so the graph optimizer tries to first run everything on CPU as a constant folding step.

**Comment by Superlee506** [comment]
@ppwwyyxx  Thanks.
