### ISSUE TITLE
Reentrant DataFromList with shuffle=True?

### ISSUE THREAD

**Issue by bzamecnik** [ppwwyyxx/tensorpack#755]
This is a Usage Question/Feature Request. I can understand that DataFlows are designed mainly as pipelines with linear graphs. However, the `JoinData` operator suggests that a DataFlow might be a DAG. A symmetric `SplitData` operation is missing since it can be expressed as passing one source DataFlow to multiple DataFlow branches.

This leads me to a scenario:
```
#            / features \
# indices -+             +-data->
#            \ targets  /
#
# list of indices that can be easily shuffled
indices = DataFromList(..., shuffle=True)
# split into two branches - features and targets
features = MapData(indices, make_features)
targets = MapData(indices, make_targets)
# merge
data = JoinData([features, targets])

# other stuff for training....
data = BatchData(data, batch_size)
# possibly repeat indefinitely (for training)
data = RepeatedData(data)
```

As a user I'd expect that I can reuse the `indices` (even with shuffling) to compute the two branches independently (possibly in parallel) and then merge them while keeping the order. However in practice, each branch gets a different shuffling.

By studying the code we can se this implicit "splitting" is called "reentrancy" and some kinds of DataFlow do not support it (see `DataFlowReentrantGuard`) but there simple DataFlow operator should have no problem with it.

As for `DataFromList` it shuffles the indices at each `get_data()` call (not only at `reset_state()`). Thus multiple branches get different ordering. We could move that shuffling to `reset_state()` to fix the problem. But then there's still a problem with combination with `RepeatedData` which calls `get_data()` multiple times and relies on shuffling at each call. Possibly we could call `reset_state()` multiple times, but I'd bet it would break other DataFlows.

A basic workaround it to avoid splitting and perform both branches in a single DataFlow but goes a bit against the design goal of isolating functionality and composability.

@ppwwyyxx Have you any idea how to use DataFlows in such a scenario? Thanks a lot!

TensorPack version: master (9bcf561c).

**Comment by ppwwyyxx** [comment]
DataFlow is meant to be stateless when they could. i.e., calling `get_data` twice is allowed and is designed to return two iterators that have no relations with each other. Therefore the behavior you're seeing is expected. Certain DataFlow cannot be made stateless and therefore they are marked not reentrant.

Since DataFlow is stateless, then the one and the only consumer of a DataFlow can keep ownership and reuse a data point. Therefore to do this you need to use something like `MapData(indices, lambda x: make_features(x) + make_targets(x))`.

I think considering it as a graph doesn't help and its behavior is indeed different from tensorflow iterators. They are just iterators.

**Comment by ppwwyyxx** [comment]
Closing since things are working as expected.
