### ISSUE TITLE
How to actually use the weights of trained Dorefa with low bit-width representation?

### ISSUE THREAD

**Issue by jonkoi** [ppwwyyxx/tensorpack#777]
Suppose I have trained a DorefaNet and have the "quantized" weights . How should I proceed to have the weights represented by few bits and have low-precision computation performed during inference with a general purpose cpu?

Sorry that this question is not related to tensorpack usage. But this implementation problem has bugging me for a while now. I have looked into Tensorflow quantization but it does not seem to be what I am looking for. I hope you can share some insights.

[gemmlowp](https://github.com/google/gemmlowp) and [BMXNet](https://arxiv.org/abs/1705.09864) look promising.

Thanks

**Comment by jonkoi** [comment]
Sorry for being confusing.

As i understand it, and correct me if i am wrong, the final weights are still stores in floats and have floating point gemm performed on them. I wanted to ask if you know of a way or a framewiork of compressing these weights to int8 or lower and have low precision gemm performed on them.

**Comment by ppwwyyxx** [comment]
If you're looking for kernel implementation, https://github.com/caffe2/caffe2/tree/master/caffe2/mobile/contrib/ulp2 contains some of the best open source ones I know.

gemmlowp only works with 8 bit and is quite slow. I don't know about BMXNet.

**Comment by asjmasjm** [comment]
Sorry to response to this topic which has been marked as unrelated so long. I am wondering if there are any float tensors in the quantized network. Once the quantized weights are trained, we either fixed-point them along with the activation values and do fixed-point calculations or only do the fixed-point in the convolution and perform the float-to-fixed-point conversion many times. The 2nd method seems unreasonable to convert the format frequently but the 1st method might introduce the extra error caused by fixed-point. I tried w4a4 and the error from fixed-point degraded the result a lot more compared to fixed-point w8a8. I am not sure the correct way to use the real quantized weights.

**Comment by asjmasjm** [comment]
And the ulp seemed to apply the 2nd method.
https://github.com/pytorch/pytorch/blob/9a7bcacc275cc4aa4107598ab0305cdcac09d3e4/caffe2/mobile/contrib/ulp2/ulp_neon.cc#L14
