### ISSUE TITLE
trigger callbacks with current session-arg

### ISSUE THREAD

**Issue by PatWie** [ppwwyyxx/tensorpack#95]
Can you add to
````
self.trigger_epoch()
````
the current session as one argument to use the `OnlinePredictor()`. `tf.get_default_session()` gives a None.

It would help to do sth like
````python
class OnlineSaving(Callback):
    def __init__(self):
        sess = tf.get_default_session()
        self.predictor = OnlinePredictor(sess, ['noise', 'code'], ['generator/fake_samples'], return_input=False)
````
after each epoch. 

````python
def _trigger_epoch(self):
        # by default, add this two stat
        self.predictor(...)
````

**Comment by ppwwyyxx** [comment]
\_\_init\_\_ usually should do nothing interesting because it is executed even before you had a TrainConfig.

To access the session you can use `self.trainer.sess` inside Callback. This is available after (included when) setup_graph is called.
The session is the default session in before_train, trigger_epoch, after_train, but not in setup_graph (because when graph is not finalized there is not a valid session).

-----------
About your task, if you want to do prediction, probably it's easier to use `trainer.get_predict_func`. It will return an OnlinePredictor in a separate tower with is_training=False. But if you don't want that for some reason you can certainly create the OnlinePredictor yourself, in either setup_graph or before_train.

**Comment by PatWie** [comment]
Alright
````python
def _setup_graph(self):
        self.pred = self.trainer.get_predict_func(['noise', 'code'], ['generator/fake_samples'])
````
is perfect!
